openapi: 3.0.3
info:
  title: hackathon24spring02-data-server
  version: 1.0.0
  description: ハッカソンで作るオンラインゲーム用の、AIへのリクエストやプレイヤーの統計情報などを管理するAPIサーバー
  contact:
    name: pikachu0310
    url: 'https://github.com/pikachu0310/hackathon24spring02-data-server'
servers:
  - url: 'http://localhost:8080/api'
    description: ローカル環境
  - url: 'https://YOUR_PRODUCTION_URL'
    description: 本番環境
tags:
  - name: items
    description: アイテムAPI
  - name: mech
    description: 自機API
paths:
  /ping:
    get:
      summary: サーバーの生存確認
      operationId: pingServer
      responses:
        '200':
          description: Pong
          content:
            text/plain:
              schema:
                type: string
                example: pong
  /test:
    get:
      summary: テスト用
      operationId: test
      responses:
        '200':
          description: OK

  /items:
    get:
      summary: アイテムを取得
      operationId: createItem
      tags:
        - items
      responses:
        '200':
          description: 成功 - アイテム取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Not Found

  /items/{itemId}:
    get:
      summary: アイテムを取得
      operationId: getItem
      tags:
        - items
      parameters:
        - in: path
          name: itemId
          required: true
          schema:
            type: string
            format: uuid
          description: アイテムID
      responses:
        '200':
          description: 成功 - アイテム取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Not Found

  /items/combine:
    post:
      summary: アイテムを合成
      operationId: combineItems
      tags:
        - items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CombineItemsRequest'
      responses:
        '200':
          description: 成功 - 合成アイテム取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Not Found

  /mech/merge:
    post:
      summary: アイテムを自機に合成
      operationId: mergeItemToMech
      tags:
        - mech
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MergeRequest'
      responses:
        '200':
          description: 成功 - 合成後の自機パラメーター
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mech'
        '404':
          description: Not Found

components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: アイテムID
        name:
          type: string
          description: アイテムの名前
        description:
          type: string
          description: アイテムのフレーバーテキスト
        attribute:
          type: integer
          description: アイテムの属性 (1~6の整数)
        rarity:
          type: integer
          description: 強さ度合い(レア度) (0~1の数字)
      required:
        - id
        - name
        - description
        - attribute
        - rarity

    Mech:
      type: object
      properties:
        defense:
          type: number
          description: プレイヤー防御力
        health:
          type: number
          description: プレイヤーhp
        maxHealth:
          type: number
          description: プレイヤー最大hp
        downTime:
          type: number
          description: healthが0になった時に動けなくなる時間
        hpRegenSpeed:
          type: number
          description: hpを1回復するのにかかる時間(ミリ秒)
        mass:
          type: number
          description: プレイヤーの質量
        bounciness:
          type: number
          description: プレイヤーの反発係数
        friction:
          type: number
          description: プレイヤーの摩擦力
        power:
          type: number
          description: プレイヤーの通常移動時の力の強さ
        size:
          type: number
          description: プレイヤーの大きさ
        dashCooldownTime:
          type: number
          description: プレイヤーのダッシュ操作のクールダウン時間
        dashArrowFillRate:
          type: number
          description: プレイヤーの矢印のたまる時間の速さ
        dashArrowMaxLength:
          type: number
          description: プレイヤーの矢印の最大の長さ
        dashAccelerationDuration:
          type: number
          description: 突き操作の加速の時間の長さ
        dashMaxForce:
          type: number
          description: 突きの最大の力
        bulletAttack:
          type: number
          description: 弾の攻撃力
        bulletNumber:
          type: number
          description: 一回のクリックで出す弾の数
        bulletAngle:
          type: number
          description: 弾のぶれる範囲
        bulletSpeed:
          type: number
          description: 弾の速さ
        bulletAliveTime:
          type: number
          description: 弾の残る時間
        bulletInterval:
          type: number
          description: 弾の射撃間隔
        bulletSize:
          type: number
          description: 弾の大きさ
        recoilForce:
          type: number
          description: 反動の大きさ
      required:
        - defense
        - health
        - maxHealth
        - downTime
        - hpRegenSpeed
        - mass
        - bounciness
        - friction
        - power
        - size
        - dashCooldownTime
        - dashArrowFillRate
        - dashArrowMaxLength
        - dashAccelerationDuration
        - dashMaxForce
        - bulletAttack
        - bulletNumber
        - bulletAngle
        - bulletSpeed
        - bulletAliveTime
        - bulletInterval
        - bulletSize
        - recoilForce

    MergeRequest:
      type: object
      properties:
        mech:
          $ref: '#/components/schemas/Mech'
        item:
          $ref: '#/components/schemas/Item'
      required:
        - mech
        - item

    CombineItemsRequest:
      type: object
      properties:
        item1_name:
          type: string
          description: 合成する最初のアイテムの名前
        item1_description:
          type: string
          description: 合成する最初のアイテムの説明文
        item2_name:
          type: string
          description: 合成する二番目のアイテムの名前
        item2_description:
          type: string
          description: 合成する二番目のアイテムの説明文
      required:
        - item1_name
        - item1_description
        - item2_name
        - item2_description
